// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAENzd-6C5xNGVfLuWm8_oTtpBZ9cWNK4Q',
    appId: '1:699840047623:web:07f19901ce7b5330f0d8a2',
    messagingSenderId: '699840047623',
    projectId: 'chat-app-529ba',
    authDomain: 'chat-app-529ba.firebaseapp.com',
    storageBucket: 'chat-app-529ba.appspot.com',
    measurementId: 'G-H4H2MR1E1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxeUW_6rn_CWA_4BKCmGGUtFcoUAGrvtM',
    appId: '1:699840047623:android:6e05aef01a1be187f0d8a2',
    messagingSenderId: '699840047623',
    projectId: 'chat-app-529ba',
    storageBucket: 'chat-app-529ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0np1H-b50IgEIeECQvy8OBb9owKih28A',
    appId: '1:699840047623:ios:aeaac4c481b21664f0d8a2',
    messagingSenderId: '699840047623',
    projectId: 'chat-app-529ba',
    storageBucket: 'chat-app-529ba.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0np1H-b50IgEIeECQvy8OBb9owKih28A',
    appId: '1:699840047623:ios:aeaac4c481b21664f0d8a2',
    messagingSenderId: '699840047623',
    projectId: 'chat-app-529ba',
    storageBucket: 'chat-app-529ba.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAENzd-6C5xNGVfLuWm8_oTtpBZ9cWNK4Q',
    appId: '1:699840047623:web:f9dd164abcf2b9fff0d8a2',
    messagingSenderId: '699840047623',
    projectId: 'chat-app-529ba',
    authDomain: 'chat-app-529ba.firebaseapp.com',
    storageBucket: 'chat-app-529ba.appspot.com',
    measurementId: 'G-3LB1M9Q0TG',
  );

}